# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'buildv3.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from matplotlib.figure import Figure
from matplotlib.backends.backend_qt5agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("background-color: rgb(120, 120, 120);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(250, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Acqsetlabel = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Acqsetlabel.sizePolicy().hasHeightForWidth())
        self.Acqsetlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Acqsetlabel.setFont(font)
        self.Acqsetlabel.setObjectName("Acqsetlabel")
        self.verticalLayout_2.addWidget(self.Acqsetlabel)
        self.widget_6 = QtWidgets.QWidget(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setMinimumSize(QtCore.QSize(325, 0))
        self.widget_5.setObjectName("widget_5")
        self.formLayout = QtWidgets.QFormLayout(self.widget_5)
        self.formLayout.setObjectName("formLayout")
        self.nsampleslabel = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.nsampleslabel.setFont(font)
        self.nsampleslabel.setObjectName("nsampleslabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.nsampleslabel)
        self.nsamplesinput = QtWidgets.QLineEdit(self.widget_5)
        self.nsamplesinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nsamplesinput.setObjectName("nsamplesinput")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.nsamplesinput)
        self.nspectralabel = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.nspectralabel.setFont(font)
        self.nspectralabel.setObjectName("nspectralabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nspectralabel)
        self.nspectrainput = QtWidgets.QLineEdit(self.widget_5)
        self.nspectrainput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nspectrainput.setObjectName("nspectrainput")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.nspectrainput)
        self.fslabel = QtWidgets.QLabel(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.fslabel.setFont(font)
        self.fslabel.setObjectName("fslabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.fslabel)
        self.fsinput = QtWidgets.QLineEdit(self.widget_5)
        self.fsinput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fsinput.setObjectName("fsinput")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fsinput)
        self.verticalLayout_3.addWidget(self.widget_5)
        self.acquirebutton = QtWidgets.QPushButton(self.widget_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.acquirebutton.sizePolicy().hasHeightForWidth())
        self.acquirebutton.setSizePolicy(sizePolicy)
        self.acquirebutton.setMinimumSize(QtCore.QSize(325, 50))
        self.acquirebutton.setMaximumSize(QtCore.QSize(325, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.acquirebutton.setFont(font)
        self.acquirebutton.setAutoFillBackground(False)
        self.acquirebutton.setStyleSheet("color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;\n"
"background-color: qlineargradient(spread:reflect, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(0, 154, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.acquirebutton.setObjectName("acquirebutton")
        self.verticalLayout_3.addWidget(self.acquirebutton)
        self.verticalLayout_2.addWidget(self.widget_6)
        self.verticalLayout.addWidget(self.widget_4)
        self.widget_3 = QtWidgets.QWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(350, 0))
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.widget_9 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_9.sizePolicy().hasHeightForWidth())
        self.widget_9.setSizePolicy(sizePolicy)
        self.widget_9.setMinimumSize(QtCore.QSize(325, 0))
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_4.addWidget(self.widget_9)
        self.Cantdimlabel = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Cantdimlabel.sizePolicy().hasHeightForWidth())
        self.Cantdimlabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Cantdimlabel.setFont(font)
        self.Cantdimlabel.setObjectName("Cantdimlabel")
        self.verticalLayout_4.addWidget(self.Cantdimlabel)
        self.widget_12 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_12.sizePolicy().hasHeightForWidth())
        self.widget_12.setSizePolicy(sizePolicy)
        self.widget_12.setMinimumSize(QtCore.QSize(325, 0))
        self.widget_12.setObjectName("widget_12")
        self.formLayout_3 = QtWidgets.QFormLayout(self.widget_12)
        self.formLayout_3.setObjectName("formLayout_3")
        self.widthedit = QtWidgets.QLineEdit(self.widget_12)
        self.widthedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.widthedit.setObjectName("widthedit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.widthedit)
        self.lengthedit = QtWidgets.QLineEdit(self.widget_12)
        self.lengthedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lengthedit.setText("")
        self.lengthedit.setObjectName("lengthedit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lengthedit)
        self.lengthlabel = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lengthlabel.sizePolicy().hasHeightForWidth())
        self.lengthlabel.setSizePolicy(sizePolicy)
        self.lengthlabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.lengthlabel.setFont(font)
        self.lengthlabel.setObjectName("lengthlabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lengthlabel)
        self.widthlabel = QtWidgets.QLabel(self.widget_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widthlabel.sizePolicy().hasHeightForWidth())
        self.widthlabel.setSizePolicy(sizePolicy)
        self.widthlabel.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        self.widthlabel.setFont(font)
        self.widthlabel.setObjectName("widthlabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.widthlabel)
        self.uncertlabel = QtWidgets.QLabel(self.widget_12)
        self.uncertlabel.setObjectName("uncertlabel")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.uncertlabel)
        self.uncertedit = QtWidgets.QLineEdit(self.widget_12)
        self.uncertedit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.uncertedit.setObjectName("uncertedit")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.uncertedit)
        self.verticalLayout_4.addWidget(self.widget_12)
        self.widget_8 = QtWidgets.QWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_8.sizePolicy().hasHeightForWidth())
        self.widget_8.setSizePolicy(sizePolicy)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.textEdit = QtWidgets.QTextEdit(self.widget_8)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout_6.addWidget(self.textEdit)
        self.verticalLayout_4.addWidget(self.widget_8)
        self.FitParamlabel = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FitParamlabel.setFont(font)
        self.FitParamlabel.setObjectName("FitParamlabel")
        self.verticalLayout_4.addWidget(self.FitParamlabel)
        self.paramtable = QtWidgets.QTableWidget(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.paramtable.sizePolicy().hasHeightForWidth())
        self.paramtable.setSizePolicy(sizePolicy)
        self.paramtable.setMinimumSize(QtCore.QSize(325, 180))
        self.paramtable.setMaximumSize(QtCore.QSize(16777215, 200))
        self.paramtable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramtable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.paramtable.setRowCount(6)
        self.paramtable.setColumnCount(3)
        self.paramtable.setObjectName("paramtable")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.paramtable.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.paramtable.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.paramtable.setItem(0, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.paramtable.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.paramtable.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.paramtable.setItem(1, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.paramtable.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(2, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.paramtable.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(3, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(3, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.paramtable.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(4, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(4, 2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        item.setFont(font)
        self.paramtable.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(5, 1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        item.setFont(font)
        self.paramtable.setItem(5, 2, item)
        self.paramtable.horizontalHeader().setVisible(False)
        self.paramtable.horizontalHeader().setHighlightSections(False)
        self.paramtable.verticalHeader().setVisible(False)
        self.paramtable.verticalHeader().setHighlightSections(False)
        self.verticalLayout_4.addWidget(self.paramtable)
        self.verticalLayout.addWidget(self.widget_3)
        self.horizontalLayout.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Ainputlabel = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Ainputlabel.sizePolicy().hasHeightForWidth())
        self.Ainputlabel.setSizePolicy(sizePolicy)
        self.Ainputlabel.setMinimumSize(QtCore.QSize(0, 50))
        self.Ainputlabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Ainputlabel.setFont(font)
        self.Ainputlabel.setObjectName("Ainputlabel")
        self.verticalLayout_5.addWidget(self.Ainputlabel)
        self.figure = Figure(tight_layout=True, dpi=100)
        self.axes = self.figure.add_subplot(111)
        self.axes.set_xlabel('Time (ms)')
        self.axes.set_ylabel('Voltage (V)')
        self.ainput = FigureCanvas(self.figure)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ainput.sizePolicy().hasHeightForWidth())
        self.ainput.setSizePolicy(sizePolicy)
        self.ainput.setMinimumSize(QtCore.QSize(0, 200))
        self.ainput.setMaximumSize(QtCore.QSize(16777215, 200))
        self.ainput.setObjectName("ainput")
        self.verticalLayout_5.addWidget(self.ainput)
        self.Pspectralabel = QtWidgets.QLabel(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Pspectralabel.sizePolicy().hasHeightForWidth())
        self.Pspectralabel.setSizePolicy(sizePolicy)
        self.Pspectralabel.setMinimumSize(QtCore.QSize(0, 50))
        self.Pspectralabel.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Pspectralabel.setFont(font)
        self.Pspectralabel.setObjectName("Pspectralabel")
        self.verticalLayout_5.addWidget(self.Pspectralabel)
        self.figure2 = Figure(tight_layout=True, dpi=100)
        self.axes2 = self.figure2.add_subplot(111)
        self.axes2.set_xlabel('Frequency (Hz)')
        self.axes2.set_ylabel('Power')
        self.mplspectra = FigureCanvas(self.figure2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mplspectra.sizePolicy().hasHeightForWidth())
        self.mplspectra.setSizePolicy(sizePolicy)
        self.mplspectra.setObjectName("mplspectra")
        self.verticalLayout_5.addWidget(self.mplspectra)
        self.navi_toolbar=NavigationToolbar(self.mplspectra,self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        self.verticalLayout_5.addWidget(self.navi_toolbar)
        self.widget_7 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_7.sizePolicy().hasHeightForWidth())
        self.widget_7.setSizePolicy(sizePolicy)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 60))
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.selectButton = QtWidgets.QPushButton(self.widget_7)
        self.selectButton.setMinimumSize(QtCore.QSize(94, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.selectButton.setFont(font)
        self.selectButton.setStyleSheet("color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;")
        self.selectButton.setObjectName("selectButton")
        self.horizontalLayout_2.addWidget(self.selectButton)
        self.fitButton = QtWidgets.QPushButton(self.widget_7)
        self.fitButton.setMinimumSize(QtCore.QSize(94, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.fitButton.setFont(font)
        self.fitButton.setStyleSheet("color: #333;\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;")
        self.fitButton.setObjectName("fitButton")
        self.horizontalLayout_2.addWidget(self.fitButton)
        self.calculatebutton = QtWidgets.QPushButton(self.widget_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculatebutton.sizePolicy().hasHeightForWidth())
        self.calculatebutton.setSizePolicy(sizePolicy)
        self.calculatebutton.setMinimumSize(QtCore.QSize(50, 50))
        self.calculatebutton.setMaximumSize(QtCore.QSize(150, 50))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.calculatebutton.setFont(font)
        self.calculatebutton.setStyleSheet("color: #333;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));\n"
"border: 2px solid #555;\n"
"border-radius: 11px;\n"
"padding: 5px;\n"
"background: qradialgradient(cx: 0.3, cy: -0.4,\n"
"fx: 0.3, fy: -0.4,\n"
"radius: 1.35, stop: 0 #fff, stop: 1 #888);\n"
"min-width: 80px;\n"
"background-color: qlineargradient(spread:pad, x1:1, y1:1, x2:1, y2:0, stop:0 rgba(255, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.calculatebutton.setObjectName("calculatebutton")
        self.horizontalLayout_2.addWidget(self.calculatebutton)
        self.verticalLayout_5.addWidget(self.widget_7)
        self.horizontalLayout.addWidget(self.widget_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1000, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Raw_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Raw_Data.setObjectName("actionLoad_Raw_Data")
        self.actionLoad_Power_Spectra = QtWidgets.QAction(MainWindow)
        self.actionLoad_Power_Spectra.setObjectName("actionLoad_Power_Spectra")
        self.actionSave_Raw_Data = QtWidgets.QAction(MainWindow)
        self.actionSave_Raw_Data.setObjectName("actionSave_Raw_Data")
        self.actionSave_Power_Spectra = QtWidgets.QAction(MainWindow)
        self.actionSave_Power_Spectra.setObjectName("actionSave_Power_Spectra")
        self.menuFile.addAction(self.actionLoad_Raw_Data)
        self.menuFile.addAction(self.actionLoad_Power_Spectra)
        self.menuFile.addAction(self.actionSave_Raw_Data)
        self.menuFile.addAction(self.actionSave_Power_Spectra)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Sader Calibration"))
        self.Acqsetlabel.setText(_translate("MainWindow", "Acquisition Settings"))
        self.nsampleslabel.setText(_translate("MainWindow", "Number of Samples"))
        self.nspectralabel.setText(_translate("MainWindow", "Number of Spectra"))
        self.fslabel.setText(_translate("MainWindow", "Sampling Rate"))
        self.acquirebutton.setText(_translate("MainWindow", "Acquire"))
        self.Cantdimlabel.setText(_translate("MainWindow", "Cantilever Dimensions"))
        self.lengthlabel.setText(_translate("MainWindow", "Length"))
        self.widthlabel.setText(_translate("MainWindow", "Width"))
        self.uncertlabel.setText(_translate("MainWindow", "Uncertainty"))
        self.uncertedit.setText(_translate("MainWindow", "1.25"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">* The default uncertainty is set to 1/2 the minimum division on the reticle using a 40x objective (in um).</p></body></html>"))
        self.FitParamlabel.setText(_translate("MainWindow", "Fit Parameters"))
        __sortingEnabled = self.paramtable.isSortingEnabled()
        self.paramtable.setSortingEnabled(False)
        item = self.paramtable.item(0, 0)
        item.setText(_translate("MainWindow", "Parameters"))
        item = self.paramtable.item(0, 1)
        item.setText(_translate("MainWindow", "Values"))
        item = self.paramtable.item(0, 2)
        item.setText(_translate("MainWindow", "StDev"))
        item = self.paramtable.item(1, 0)
        item.setText(_translate("MainWindow", "f0"))
        item = self.paramtable.item(2, 0)
        item.setText(_translate("MainWindow", "A"))
        item = self.paramtable.item(3, 0)
        item.setText(_translate("MainWindow", "Q"))
        item = self.paramtable.item(4, 0)
        item.setText(_translate("MainWindow", "baseline"))
        item = self.paramtable.item(5, 0)
        item.setText(_translate("MainWindow", "kcant"))
        self.paramtable.setSortingEnabled(__sortingEnabled)
        self.Ainputlabel.setText(_translate("MainWindow", "Analog Input"))
        self.Pspectralabel.setText(_translate("MainWindow", "Power Spectrum"))
        self.selectButton.setText(_translate("MainWindow", "Select"))
        self.fitButton.setText(_translate("MainWindow", "Fit"))
        self.calculatebutton.setText(_translate("MainWindow", "Calculate"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Raw_Data.setText(_translate("MainWindow", "Load Raw Data"))
        self.actionLoad_Power_Spectra.setText(_translate("MainWindow", "Load Power Spectra"))
        self.actionSave_Raw_Data.setText(_translate("MainWindow", "Save Raw Data"))
        self.actionSave_Power_Spectra.setText(_translate("MainWindow", "Save Power Spectra"))

